### ISSUE TITLE
Local file paths not working

### ISSUE THREAD

**Issue by ChocopieKewpie** [manaakiwhenua/vector2dggs#10]
Pointing to a local file will raise a :s qlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string 'ratings-nrc.gpkg'.
Problem seems to lie on line 275, assuming that an empty is not None.

**Comment by alpha-beta-soup** [comment]
Just fixed in v0.3.1. For the record, it would have worked with `file://ratings-nrc.gpkg`
