### ISSUE TITLE
--keepattributes improperly indexing id

### ISSUE THREAD

**Issue by ChocopieKewpie** [manaakiwhenua/vector2dggs#16]
Indexed output with -k will generate a new fid starting with 0 even if data starts with fid 1. Resulting output will therefore have misassigned fid (fid-1).

**Comment by alpha-beta-soup** [comment]
Does that matter? The original fields, including the `--id_field` will br present, allowing any association to be built.

And what happens with `-k id_field blah`?

**Comment by ChocopieKewpie** [comment]
Totally forgot this method was implemented
